export const API = {
  AUTH: {
    LOGIN: "/auth/login",
    ME: "/authz/me",
  },
  EMPLOYEES: "/employees",
  DEPARTMENTS: "/departments",
  POSITIONS: "/positions",
  LEAVE_REQUESTS: "/leave-requests",
  LEAVE_BALANCES: "/leave-balances",
  HOLIDAYS: "/holidays",
  OVERTIME: "/overtime",
  PAYROLL_PERIODS: "/payroll-periods",
  PAYROLL_RUNS: "/payroll-runs",
  PAYSLIPS: "/payslips",
  TIME_ENTRIES: "/time-entries",
  RECRUITMENT: {
    CANDIDATES: "/candidates",
    JOB_POSTINGS: "/job-postings",
    APPLICATIONS: "/applications",
    INTERVIEWS: "/interviews",
    CONVERT: "/recruitment/applications",
  },
  TRAINING: {
    COURSES: "/training/courses",
    ENROLLMENTS: "/training/enrollments",
    ENROLL: "/training/enroll",
  },
  ONBOARDING: {
    TEMPLATES: "/onboarding/templates",
    TASKS: "/onboarding/tasks",
    START: "/onboarding/start",
  },
  DOCUMENTS: "/documents",
  DOCUMENTS_UPLOAD: "/documents/upload",
  DOCUMENTS_MINE: "/documents/mine",
  ASSETS: "/assets",
  ANNOUNCEMENTS: "/announcements",
  AUDIT_LOGS: "/audit-logs",
  DASHBOARD: {
    SUMMARY: "/dashboard/summary",
    ACTIVITIES: "/dashboard/activities",
    HEADCOUNT_BY_DEPT: "/dashboard/headcount-by-department",
    DEPT_DISTRIBUTION: "/dashboard/department-distribution",
  },
  AUTHZ: {
    PERMISSIONS: "/authz/permissions",
    ROLES: "/authz/roles",
    USERS: "/authz/users",
    SCOPES: "/authz/scopes",
    AUDIT: "/authz/audit",
    IDP_MAPPINGS: "/authz/idp-mappings",
  },
  PERFORMANCE: {
    CYCLES: "/performance/cycles",
  },
  SELF: {
    PROFILE: "/self/profile",
    PAYSLIPS: "/self/payslips",
    LEAVE_BALANCES: "/self/leave-balances",
    LEAVE_REQUESTS: "/self/leave-requests",
    TIME_ENTRIES: "/self/time-entries",
    CLOCK_IN: "/self/time-entries/clock-in",
    CLOCK_OUT: "/self/time-entries/clock-out",
  },
} as const;
