ALTER TABLE employee ADD COLUMN position_id uuid;
ALTER TABLE employee ADD COLUMN email varchar(255);
ALTER TABLE employee ADD COLUMN phone varchar(20);
ALTER TABLE employee ADD COLUMN date_of_birth date;
ALTER TABLE employee ADD COLUMN gender varchar(10);
ALTER TABLE employee ADD COLUMN national_id varchar(20);
ALTER TABLE employee ADD COLUMN address text;
ALTER TABLE employee ADD COLUMN bank_account varchar(30);
ALTER TABLE employee ADD COLUMN tax_code varchar(20);
